# Generated by Django 4.2.23 on 2025-12-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=150)),
                ('address', models.TextField(max_length=150)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
